name: Resume Builder CD

on:
  workflow_run:
    workflows: ["Resume Builder CI"]
    types:
      - completed
    branches:
      - master

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull rajwinderkaur061/resume-ai:latest
            docker stop resume-ai-container || true
            docker rm resume-ai-container || true
            docker run -d -p 8080:8080 --name resume-ai-container rajwinderkaur061/resume-ai:latest
